# Site Settings
title:               David C. Brown
tagline:             Full Stack Software Engineer Consultant.
description:
baseurl:             ""
url:                 "http://davidcbrown.io"
github:
  url:               "https://TheOneTheOnlyDavidBrown.github.io/davidcbrownio"
author:
  name:              "David C. Brown"
  email:             "me@davidcbrown.io"
  twitter:           "TheOneTheOnlyDB"
  github:            "TheOneTheOnlyDavidBrown"
  linkedin:          "davidbrownucf"
  pictureurl:        "https://avatars0.githubusercontent.com/u/1423875"
navigation:
- title: About
  url: /about
- title: Musings
  url: /musings
- title: Open-Source
  url: /open-source-contributions
- title: Contact
  url: /contact

paginate:            5
disqus:              "davidcbrown-io"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
future:              false
timezone:            "America/New_York"
