# Site Settings
title:               David C. Brown
tagline:             Full-stack Software Engineer in Orlando, FL
description:
baseurl:            #"/Lagrange"
url:                #"https://TheOneTheOnlyDavidBrown.github.io"
github:
  url:               #"https://TheOneTheOnlyDavidBrown.github.io/davidcbrownio"
author:
  name:              "David C. Brown"
  email:             "me@davidcbrown.io"
  twitter:           "TheOneTheOnlyDB"
  github:            "TheOneTheOnlyDavidBrown"
  linkedin:          "davidbrownucf"
navigation:
- title: About
  url: /about
- title: Musings
  url: /musings
- title: Open-Source
  url: /open-source-contributions
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
