# Site Settings
title:               David C. Brown
tagline:             Software Engineer. Hacker. Not a lemming.
description:
baseurl:             "/davidcbrownio"
url:                 "https://TheOneTheOnlyDavidBrown.github.io"
github:
  url:               "https://TheOneTheOnlyDavidBrown.github.io/davidcbrownio"
author:
  name:              "David C. Brown"
  email:             "me@davidcbrown.io"
  twitter:           "TheOneTheOnlyDB"
  github:            "TheOneTheOnlyDavidBrown"
  linkedin:          "davidbrownucf"
navigation:
- title: About
  url: /about
- title: Musings
  url: /musings
- title: Open-Source
  url: /open-source-contributions
- title: Contact
  url: /contact

paginate:            5
disqus:              "davidcbrown-io"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
future:              false
